# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://coog.ie
title: "Stephen Coogan"
# subtitle: "Front-end Web Developer living in Dublin, Ireland."
author: "Stephen Coogan"
simple_search: http://google.com/search
description: "Stephen Coogan is a Front-end Web Developer who currently lives in Dublin, Ireland. He loves code, games, and coffee."

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: hello@coog.ie

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
paginate_path: "blog/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html, asides/twitter.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Oscailte Theme Settings
oscailte:
    hire:
        visible:
            footer: true
            sidebar: true
        available: false
        vibrant: true
        footer-cols: 6
        message: "Not looking for new opportunities at this time"
    social:
        visible: true
        title: # Defaults to "Follow me!" if not present
        adn: # App.net
        coinbase:
        dribbble:
        facebook:
            user:
            app_id: 100003785576014
        github:
            user: coogie
            show_profile_link: true
        googleplus: 100468279968854962736
        hackernews:
        keybase: coogie
        linkedin: coogie
        pinterest:
        reddit:
        stackoverflow:
        twitter:
            user: coog_ie
            widget:
                is_shown: true
                show_profile_link: true
                widget_id: 550812041918021632
        youtube:

# Github repositories
github_user: coogie
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: coog_ie
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 100468279968854962736
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: coogie
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-36133007-1

# Facebook Like
facebook_like: false
