author: Stephen Coogan
email: hello@coog.ie
description: >-
  Stephen Coogan is a Front-end Web Developer currently living in Dublin, Ireland.
  He loves code, games, and coffee.
  Is occasionally serious.
lang: en_GB
title: Stephen Coogan
subtitle: Front-end Web Developer
url: https://coog.ie
permalink: /blog/:year/:month/:day/:title/
show_excerpts: true

# Integrations
analytics_id: UA-36133007-1
disqus:
  shortname: coogie

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme

# Theme and Theme Configs
remote_theme: "coogie/oscailte"
header_pages:
  - index.md
  - blog.md
  - contact.md
  - cv.md
oscailte:
  analytics:
    google: UA-36133007-1
  strings:
    hero_title: Hi there!<br> I'm Stephen, a Front-end Web Developer from Dublin, Ireland.
  social:
    github: coogie
    keybase: coogie
    linkedin: coogie
    twitter: coog_ie
    rss: rss

sass:
  # style: expanded
  style: compressed

webrick:
  headers:
    Cache-Control: public, max-age=15768000